import Head from "next/head";
import styles from "../styles/Home.module.scss";
import Container from "../components/container";
import Heading from "../components/heading";

export default function Home() {
  return (
    <Container>
      <Head>
        <title>A Next App Skeleton</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Heading type={"h1"}>A Next.js Skeleton By Dillon Smith</Heading>
      </main>
    </Container>
  );
}
